### ISSUE TITLE
Практика работы с массивами

### ISSUE THREAD

**Issue by Romashine** [Romashine/test#1]
1. редактирование в массиве
2. добавление в массив
3. удаление из массива
4. фильтр в массиве
5. критерий ввода данных

**Comment by microshine** [comment]
- [ ] Добавить во все функции обработки массива первым параметром обрабатываемый массив
```jabascript
// Пример
function arrayFind(array, dayWanted) {
    // ...
}
```

- [ ] создать исполняемый скрипт с демонстрацией обработки нескольких массивов данных

**Comment by Romashine** [comment]
- [ ] убрать eror

- [ ] добавить return

- [ ] отредактировать описания

**Comment by microshine** [comment]
Отлично
